### PR TITLE
Style branch

### PR DESCRIPTION
**Pull request by oniso20**
# Here are some major changes made on this branch;

## Dependency
JSON server is installed and used as a dependency for fetching the data. The data is available locally in the db.json file in the data folder. See more about the json-server here - https://www.npmjs.com/package/json-server.

The data was coming in as an object after fetching it as expected but it also presented some challenges in working with it.
The data is fetched in the APP.js file.

The input data is being used in OptionsCard.js - Currently, the cards are generated based on the number of options available in the data, and the clickHandler handles getting the options on click.

## Components

Nav - The navbar component
Card - The individual cards which are filled by each guess
OptionsCard - The options for players to select from

## Hooks
useFactle.js - The major function will be used here. For now, the clickHandler is almost ready.

## Major issue

Handling the data coming in on click, the data needs a lot of cleaning.

### CODE REVIEW

**Review by corbfon — CHANGES_REQUESTED** [review]
This is a great start. I'd recommend adding the `engines` key to the `package.json` and including the version of Node.js that you're using to build the project, as I had to find the correct version. Also include `npm install` as a step in `README.md`

As far as the app itself, the spacing and setup looks great on desktop! I'd recommend taking a look at mobile styles, as the cards get cramped. Most of the users here will be on mobile, so the mobile styles will be key! For that reason, I'll request changes here, but the code and structuring here looks good (as well as your use of hooks).

**Comment by oniso20** [comment]
Hello Corbin,

Thanks for the review, I'll make the necessary changes and revert back to
you.

Best regards,
Onis Emem.

**Comment by oniso20** [comment]
Hello @corbfon,

I have made the requested adjustment;

- Add Engine keys to enforce node version
- Include `npm install` as a sted in the README.md
- Fix mobile responsiveness 

Thanks for spotting the opportunities for improvement.

Best regards,
Onis Emem.

**Review by corbfon — APPROVED** [review]
Looks good! We'll come back to do more styling later, but for now this is a great start.

**Pull request merged**
